# -*- coding: utf-8 -*-
"""climate_action.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-Ggcp0-dasIPT1D-Za35KiZwwRkxzPL
"""

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Data loading, cleaning & processing
data = pd.read_csv('carbon_emissions.csv')
data = data.dropna()

X = data[['year', 'gdp', 'population']]
y = data['co2_growth_prct']
y = np.where(y > y.mean(), 1, 0)

# Feature scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Train the model
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluation
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Visualization
plt.figure(figsize=(8,5))
plt.scatter(data['year'], data['co2_growth_prct'], color='green')
plt.title('Carbon Emissions Over Years')
plt.xlabel('Year')
plt.ylabel('CO2 Emissions')
plt.show()